# Use an official Java runtime as a parent image
FROM openjdk:11-jdk-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Build the application using Maven
RUN ./mvnw package -DskipTests

# Make port 9320 available to the world outside this container
EXPOSE 9320

# Run the application when the container launches
CMD ["java", "-jar", "target/hello-docker.jar"]